import sqlite3
from datetime import datetime
from pathlib import Path
from logger import get_logger

logger = get_logger(__name__) #logger is now logging object

#BookingDB: SQLite database class for booking management that stores booking data and status tracking
class BookingDB:
    
    def __init__(self, db_path: str = "./booking.db"): #if no args, use default booking.db. "./" = db file will be made in this dir
        self.db_path = db_path
        self._init_db() #to set up the db table directly after BookingDB() is made

    def _init_db(self): #create booking table if isnt available
        #path below will creates directory if it doesnt exist yet, so the program wont crash
        Path(self.db_path).parent.mkdir(parents = True, exist_ok = True) 

        with sqlite3.connect(self.db_path) as conn: #make a connection with sqlite3 and close connection automatically later
            cursor = conn.cursor() #activate the cursor method (give orders to sqlite3)
            #execute code within """, will be sent to sqlite3. note: id default start from 1 and will incremented
            cursor.execute("""
                CREATE TABLE IF NOT EXISTS bookings (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    booking_id TEXT UNIQUE,
                    user_id TEXT NOT NULL,
                    nama TEXT NOT NULL, 
                    lokasi TEXT NOT NULL,
                    treatment TEXT NOT NULL,
                    tanggal TEXT NOT NULL,
                    jam TEXT NOT NULL,
                    status TEXT DEFAULT 'PENDING',
                    notes TEXT ,
                    created_at TEXT NOT NULL,
                    updated_at TEXT,
                    confirmed_at TEXT
                )"""
            )
            conn.commit() #permanently save the changes to db (sqlite3)

        logger.info("Database initialized", extra={"path": self.db_path}) #note: db name = booking.db ; table name = bookings
    
    def create_booking(self, user_id: str, slots: dict): #create booking (insert data), will return booking_id if valid

        requirements = ["nama", "lokasi", "treatment", "tanggal", "jam"]
        for key in requirements:
            if key not in slots:
                raise KeyError(f"Missing required info: {key}") #KeyError: an error for a missing value in dictionary
            
        #booking_id = self.generate_booking_id()
        now = datetime.utcnow().isoformat()
        try: #use try and exception so there wont be any silent error, will know the cause of error
            with sqlite3.connect(self.db_path) as conn: #with is used bcs its safe if errors occurs (will rollback) and auto close connection
                cursor = conn.cursor()
                
                #if there's exact booking with identical user and info then dont make new, just return the value.
                cursor.execute("""
                    SELECT booking_id FROM bookings WHERE 
                    user_id = ? AND tanggal = ? AND jam = ? AND status != 'CANCELED'""", #note: CANCELED without quotes = considered as column/row name not as a string
                    (user_id, slots['tanggal'], slots['jam'])
                    )
                existed = cursor.fetchone()
                if existed:
                    logger.info("Returning existing booking", extra={"booking_id": existed[0]})
                    return existed[0]
                
                #insert without using booking id first. note: id will be incremented while executing "INSERT"
                cursor.execute("""
                    INSERT INTO bookings(
                        user_id, nama, lokasi, treatment,
                        tanggal, jam, status, created_at
                    ) VALUES (?, ?, ?, ?, ?, ?, ?, ?)""",
                    (user_id,
                    slots['nama'],
                    slots['lokasi'],
                    slots['treatment'],
                    slots['tanggal'],
                    slots['jam'],
                    'PENDING',
                    now)
                )
                #there will be gap at "id" and "booking_id" if data isnt valid, bcs id is autoincremented after the insert whether its valid or no
                row_id = cursor.lastrowid #lastrowid: sqlite3 attributes that fetch variables with type of INTEGER, PRIMARY KEY, and AUTOGENERATED (not determined by dev) which is "id"
                booking_id = f"BK{row_id:03d}" #row_id now = id, result: BK001, BK002, etc

                cursor.execute(
                    "UPDATE bookings SET booking_id = ? WHERE id = ?", #update 1 line spesific booking_id at the line of id located
                    (booking_id, row_id)
                )
                conn.commit()

                logger.info("Booking created", extra={"booking_id": booking_id, "user_id": user_id})
                return booking_id

        #if the data is wrong: NOT NULL but no value, same booking_id, invalid data type, etc      
        except sqlite3.IntegrityError as e: #use sqlite3 at the prefix bcs we only want to catch the error in database only
            logger.error("Database integrity error", extra={"error": str(e)}, exc_info=True)
            raise ValueError(f"Booking gagal: Data tidak valid") #raise to the caller function to be handled, and change the error type to ValueError
        
        #if there is any other error
        except sqlite3.Error as e: 
            logger.error("Database error", extra={"error": str(e)}, exc_info=True)
            raise #raise to the caller function to be handled

    def _row_to_dict(self, cursor, row) -> dict: #convert the tuple info to dictionary
        if not row:
            return None

        columns = [col[0] for col in cursor.description] #cursor.description is a list of tuple (tuple count depends on number of columns) with the first word in tuple is a header columns
        return dict(zip(columns, row))
        # zip(['booking_id', 'user_id', 'nama', 'lokasi'], #columns
        #     ['BK001', 'user123', 'Reni', 'Bekasi']) #row; then will convert zip to dict

    def get_booking(self, booking_id: str) -> dict: #fetch booking info using booking_id as args
        with sqlite3.connect(self.db_path) as conn:
            cursor = conn.cursor()
            cursor.execute("SELECT * FROM bookings WHERE booking_id = ?", (booking_id,)) #will return list of tuple, on this case only 1
            row_info = cursor.fetchone() #fetchone: take the first tuple (only 1 line) consist of booking info

            return self._row_to_dict(cursor, row_info) #return in dict format
    
    #return list of all booking from a user
    def get_user_bookings(self, user_id: str, status: str = None) -> list: #args: the user_id that user requested and spesific status if user wanted to
        with sqlite3.connect(self.db_path) as conn:
            cursor = conn.cursor()

            if status: #if there is spesific status to be filtered
                cursor.execute(
                    "SELECT * FROM bookings WHERE user_id = ? AND status = ? ORDER BY created_at DESC", 
                    (user_id, status) #list order is from the newest to the oldest
                )
            else:
                cursor.execute(
                    "SELECT * FROM bookings WHERE user_id = ? ORDER BY created_at DESC",
                    (user_id,) #list order is from the newest to the oldest
                )
            rows = cursor.fetchall() #fetch all the rows/bookings info that was already filtered

            return [self._row_to_dict(cursor, row) for row in rows] #for every bookings, convert to dict
    
    def update_status(self, booking_id: str, status: str, notes: str = None):
        VALID_STATUS = ['PENDING', 'CONFIRMED', 'CANCELED', 'COMPLETED']
        if status not in VALID_STATUS:
            raise ValueError(f"Invalid status: {status}") #pass the error to the caller function to be handled

        with sqlite3.connect(self.db_path) as conn:
            cursor = conn.cursor()
            now = datetime.utcnow().isoformat()

            if notes: #update status, notes, updated_at; at the spesific booking_id
                cursor.execute(
                    "UPDATE bookings SET status = ?, notes = ?, updated_at = ? WHERE booking_id = ?",
                    (status, notes, now, booking_id)
                )
            else: #update status and updated_at; at the spesific booking_id
                cursor.execute(
                    "UPDATE bookings SET status = ?, updated_at = ? WHERE booking_id = ?",
                    (status, now, booking_id)
                )

            if status == 'CONFIRMED': #update the confirmed_at; at the spesific booking_id
                cursor.execute(
                    "UPDATE bookings SET confirmed_at = ? WHERE booking_id = ?",
                    (now, booking_id)
                )
            conn.commit() #officially updated the info
            logger.info("Booking status updated", extra={"booking_id": booking_id, "status": status})
    
    #get all bookings filtered by its status, if no status then return all bookings
    def get_bookings_status(self, status: str = None) -> list:
        with sqlite3.connect(self.db_path) as conn:
            cursor = conn.cursor()
            if status:
                cursor.execute(
                    "SELECT * FROM bookings WHERE status = ? ORDER BY created_at DESC",
                    (status,)
                )
            else:
                cursor.execute("SELECT * FROM bookings ORDER BY created_at DESC")
            rows = cursor.fetchall() #rows: list of tuples

            return [self._row_to_dict(cursor, row) for row in rows] #return list of dict (1 dict = 1 booking)
    
    def delete_booking(self, booking_id: str):
        with sqlite3.connect(self.db_path) as conn:
            cursor = conn.cursor()

            cursor.execute(
                "DELETE FROM bookings WHERE booking_id = ?",
                (booking_id,)
            )
            conn.commit()
            logger.info("Booking deleted", extra={"booking_id": booking_id})

#test
if __name__ == "__main__":

    db = BookingDB()

    test_slots = {
        "nama": "Ren",
        "lokasi": "Bekasi",
        "treatment": "Facial",
        "tanggal": "2026-01-06",
        "jam": "14:00"
    }

    booking_id = db.create_booking("qwen12", test_slots)
    print(f"Created: {booking_id}")

    booking = db.get_booking(booking_id)
    print(f"Retrieved: {booking}")

    db.update_status(booking_id, "CONFIRMED", "Confirmed via WA")
    print("Updated Status")